name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository dispatch event
        run: |
          curl -XPOST -u "JCoelhoo:${{ secrets.GH_PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" \
            https://api.github.com/repos/multycloud/multy-internal/actions/workflows/deploy.yml/dispatches \
            --data '{"ref": "master"}'