name: deploy

on:
  repository_dispatch:
    types:
      - deploy
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: |
          gh api repos/:owner/multy-infra/dispatches \
              --raw-field event_type=deploy